#!/bin/bash  

rojo='\033[0;31m'
normal='\033[0m'
verde='\033[0;32m'
mkdir ejecutables
mkdir ejecutables/logs

gcc OsadaMaster/src/OsadaMaster.c -lSupport -lnivel-gui -lcurses  -lpthread -lcommons -lm -o ejecutables/server
[ -f ejecutables/server ] && echo -e "${verde}Compilamos server${normal}" || echo -e "${rojo}No compilo server :(${normal}" 


gcc PokedexCliente/main.c -DFUSE_USE_VERSION=27 -D_FILE_OFFSET_BITS=64 -lcommons -lSupport -lnivel-gui -lcurses -lpthread -lfuse  -o ejecutables/cliente
[ -f ejecutables/cliente ] && echo -e "${verde}Compilamos pokedex${normal}" || echo -e "${rojo}No compilo pokedex :(${normal}" 

gcc Mapa/src/Mapa.c -lcommons -lnivel-gui -lcurses -lpthread -lSupport -lpkmn-battle -o ejecutables/mapa
[ -f ejecutables/mapa ] && echo -e "${verde}Compilamos mapa${normal}" || echo -e "${rojo}No compilo mapa :(${normal}" 

gcc Entrenador/src/Entrenador.c -lSupport -lnivel-gui -lcommons -lcurses -lpthread  -o ejecutables/entrenador
[ -f ejecutables/entrenador ] && echo -e "${verde}Compilamos entrenador${normal}" || echo -e "${rojo}No compilo entrenador :(${normal}" 
